from .main_menu import main_menu_client, main_menu_admin, main_menu_master
from .admin_canсel import admin_cancel_mail_or_confirm, admin_cancel_mail, admin_default_cancel_add_master, \
    admin_default_cancel_confirm_add_master, admin_default_cancel_confirm_service_list, admin_default_cancel_del_master
from .phone_number import phone_number
from .user_cancel import default_cancel_appointment, default_cancel_appointment_confirm, default_cancel_user_check_logs
